import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowDownToLine, ArrowUpRight, CheckCircle2, CirclePlus, FileSpreadsheet, MoreHorizontal, RefreshCw, Trash2, Upload, Users, XCircle } from "lucide-react";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { getDashboardData } from "./dashboard.data";
import type { ActivityType, CollectionDataPoint, DashboardData } from "./dashboard.types";

const number = new Intl.NumberFormat("en-US");
const periods = [{ key: "7d", label: "7 Days" }, { key: "30d", label: "30 Days" }, { key: "3m", label: "3 Months" }, { key: "1y", label: "1 Year" }];
const activityIcons: Record<ActivityType, typeof Upload> = { import: Upload, create: CirclePlus, update: RefreshCw, delete: Trash2, warning: AlertTriangle };

function StatCard({ label, value, detail, icon: Icon, tone = "primary" }: { label: string; value: number; detail: string; icon: typeof Users; tone?: "primary" | "warning" }) {
    return <Card><CardContent className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{number.format(value)}</p><p className={`mt-2 text-xs ${tone === "warning" ? "text-amber-600 dark:text-amber-400" : "text-muted-foreground"}`}>{detail}</p></div><span className={`flex size-10 items-center justify-center rounded-lg ${tone === "warning" ? "bg-amber-500/10 text-amber-600" : "bg-primary/10 text-primary"}`}><Icon className="size-5" /></span></CardContent></Card>;
}

function CollectionOverview({ data, period, onPeriodChange }: { data: CollectionDataPoint[]; period: string; onPeriodChange: (period: string) => void }) {
    const points = data; const max = Math.max(...points.map((point) => point.count), 0); const min = Math.min(...points.map((point) => point.count), 0);
    const coordinates = points.map((point, index) => `${(index / (points.length - 1)) * 100},${100 - ((point.count - min) / Math.max(max - min, 1)) * 82 - 8}`).join(" ");
    return <Card className="lg:col-span-2"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>Collection Overview</CardTitle><p className="mt-1 text-xs text-muted-foreground">Records collected over time</p></div><div className="flex flex-wrap justify-end gap-1">{periods.map((item) => <Button key={item.key} size="sm" variant={period === item.key ? "secondary" : "ghost"} onClick={() => onPeriodChange(item.key)}>{item.label}</Button>)}</div></CardHeader><CardContent><div className="relative h-64 overflow-hidden rounded-lg bg-muted/30 p-4"><div className="absolute inset-x-4 top-4 bottom-8 flex flex-col justify-between border-y border-dashed border-border/70"><span /><span /><span /></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="relative h-full w-full" aria-label="Collection growth chart" role="img"><polyline points={coordinates} fill="none" vectorEffect="non-scaling-stroke" className="stroke-primary" strokeWidth="0.8" /><polyline points={`0,100 ${coordinates} 100,100`} fill="currentColor" opacity=".08" className="text-primary" /></svg><div className="absolute inset-x-4 bottom-2 flex justify-between text-[11px] text-muted-foreground">{points.map((point) => <span key={point.date}>{point.date}</span>)}</div></div><div className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><ArrowUpRight className="size-4 text-emerald-600" /> Collection is trending upward</div></CardContent></Card>;
}

function WardDistribution({ wards }: { wards: DashboardData["wardStatistics"] }) { const max = Math.max(...wards.map((ward) => ward.count), 1); return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Records by Ward</CardTitle><Button variant="ghost" size="sm">View all wards</Button></CardHeader><CardContent className="space-y-4">{wards.map((ward) => <div key={ward.wardId} className="space-y-1.5"><div className="flex justify-between text-sm"><span>{ward.wardName}</span><span className="font-medium">{number.format(ward.count)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${(ward.count / max) * 100}%` }} /></div></div>)}</CardContent></Card>; }

function DataQuality({ quality }: { quality: DashboardData["dataQuality"] }) { return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Data Quality</CardTitle><Button variant="outline" size="sm">Review issues</Button></CardHeader><CardContent className="space-y-4">{quality.map((item, index) => <div key={item.label} className="space-y-1.5"><div className="flex justify-between text-sm"><span>{item.label}</span><span className="font-medium">{item.percentage}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${index === 0 ? "bg-emerald-500" : index === 1 ? "bg-amber-500" : "bg-secondary"}`} style={{ width: `${item.percentage}%` }} /></div></div>)}</CardContent></Card>; }

function RecentActivity({ activities }: { activities: DashboardData["recentActivity"] }) { return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Recent Activity</CardTitle><Button variant="ghost" size="icon-sm" aria-label="More activity"><MoreHorizontal /></Button></CardHeader><CardContent className="space-y-4">{activities.map((activity) => { const Icon = activityIcons[activity.type]; return <div className="flex gap-3" key={activity.id}><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground"><Icon className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{activity.title}</p><p className="text-xs text-muted-foreground">{activity.description}</p></div><time className="shrink-0 text-right text-[11px] text-muted-foreground">{activity.timestamp}</time></div>; })}<Button variant="link" className="px-0">View all activity</Button></CardContent></Card>; }

function LatestImport({ latest }: { latest: DashboardData["latestImport"] }) { if (!latest) return <Card><CardHeader><CardTitle>Latest Import</CardTitle></CardHeader><CardContent className="py-8 text-sm text-muted-foreground">No imports have been completed yet.</CardContent></Card>; return <Card><CardHeader><CardTitle>Latest Import</CardTitle></CardHeader><CardContent><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileSpreadsheet className="size-5" /></span><div><p className="font-medium">{latest.fileName}</p><p className="mt-1 text-xs text-muted-foreground">{number.format(latest.totalRecords)} records processed</p><p className="mt-1 text-xs text-muted-foreground">Imported: {new Date(latest.createdAt).toLocaleString()}</p></div></div><div className="mt-5 grid grid-cols-3 gap-2 border-y border-border py-3 text-xs"><span className="text-emerald-600"><CheckCircle2 className="mr-1 inline size-3.5" />{number.format(latest.successfulRecords)}</span><span className="text-amber-600"><AlertTriangle className="mr-1 inline size-3.5" />{number.format(latest.incompleteRecords)}</span><span className="text-destructive"><XCircle className="mr-1 inline size-3.5" />{number.format(latest.failedRecords)}</span></div><div className="mt-4 flex flex-wrap gap-2"><Link to={`/citizens/imports/${latest.id}`}><Button variant="outline" size="sm">View import details</Button></Link><Link to="/citizens/import"><Button size="sm" icon={<Upload />}>Import new file</Button></Link></div></CardContent></Card>; }

function QuickActions() { const navigate = useNavigate(); const actions = [{ label: "Add Citizen", icon: CirclePlus, path: "/citizens/add" }, { label: "Import Data", icon: Upload, path: "/citizens/import" }, { label: "View Citizens", icon: Users, path: "/citizens/list" }, { label: "Export Data", icon: ArrowDownToLine, path: "#" }, { label: "Review Incomplete", icon: AlertTriangle, path: "#" }]; return <Card><CardHeader><CardTitle>Quick Actions</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-2">{actions.map(({ label, icon: Icon, path }) => <Button key={label} variant="outline" className="justify-start" onClick={() => path !== "#" && navigate(path)} icon={<Icon />}>{label}</Button>)}</CardContent></Card>; }

function DashboardSkeleton() { return <div className="space-y-6 animate-pulse"><div className="h-10 w-64 rounded bg-muted" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <div className="h-32 rounded-xl bg-muted" key={item} />)}</div><div className="grid gap-4 lg:grid-cols-3">{[1, 2, 3].map((item) => <div className="h-80 rounded-xl bg-muted" key={item} />)}</div></div>; }

export default function DashboardPage() {
    const [data, setData] = useState<DashboardData | null>(null); const [period, setPeriod] = useState("30d"); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [refreshing, setRefreshing] = useState(false);
    const load = async (selectedPeriod = period) => { setError(false); setRefreshing(true); try { setData(await getDashboardData(selectedPeriod)); setPeriod(selectedPeriod); } catch { setError(true); } finally { setLoading(false); setRefreshing(false); } };
    useEffect(() => { void load(); }, []);
    if (loading) return <DashboardSkeleton />;
    if (error) return <Card><CardContent className="flex flex-col items-center gap-3 py-12 text-center"><AlertTriangle className="size-8 text-amber-500" /><h1 className="text-lg font-semibold">Unable to load dashboard data</h1><p className="text-sm text-muted-foreground">Please try again.</p><Button onClick={() => void load()} isSubmitting={refreshing}>Retry</Button></CardContent></Card>;
    if (!data || data.stats.totalCitizens === 0) return <Card><CardContent className="flex flex-col items-center gap-4 py-16 text-center"><Users className="size-10 text-muted-foreground" /><h1 className="text-xl font-semibold">No collection data yet</h1><p className="text-sm text-muted-foreground">Start by adding citizens or importing an Excel file.</p><div className="flex gap-2"><Link to="/citizens/add"><Button>Add citizen</Button></Link><Link to="/citizens/import"><Button variant="outline">Import data</Button></Link></div></CardContent></Card>;
    return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-semibold tracking-tight">Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Overview of your data collection activities</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="icon" onClick={() => void load()} isSubmitting={refreshing} aria-label="Refresh dashboard"><RefreshCw /></Button><Link to="/citizens/import"><Button icon={<Upload />}>Import data</Button></Link><Link to="/citizens/add"><Button variant="outline" icon={<CirclePlus />}>Add citizen</Button></Link></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Total Citizens" value={data.stats.totalCitizens} detail="Live database count" icon={Users} /><StatCard label="Complete Records" value={data.stats.completeRecords} detail={`${data.stats.totalCitizens ? ((data.stats.completeRecords / data.stats.totalCitizens) * 100).toFixed(1) : 0}% of total records`} icon={CheckCircle2} /><StatCard label="Incomplete Records" value={data.stats.incompleteRecords} detail={`${data.stats.totalCitizens ? ((data.stats.incompleteRecords / data.stats.totalCitizens) * 100).toFixed(1) : 0}% need attention`} icon={AlertTriangle} tone="warning" /><StatCard label="Imported Records" value={data.stats.importedRecords} detail={data.latestImport ? `Last import: ${new Date(data.latestImport.createdAt).toLocaleString()}` : "No completed imports"} icon={FileSpreadsheet} /></div><div className="grid gap-4 lg:grid-cols-3"><CollectionOverview data={data.collectionOverview} period={period} onPeriodChange={(selectedPeriod) => void load(selectedPeriod)} /><WardDistribution wards={data.wardStatistics} /></div><div className="grid gap-4 lg:grid-cols-2"><DataQuality quality={data.dataQuality} /><LatestImport latest={data.latestImport} /></div><div className="grid gap-4 lg:grid-cols-2"><RecentActivity activities={data.recentActivity} /><QuickActions /></div></div>;
}
