import { useEffect, useState } from "react";
import { RefreshCw, Search, Upload, Users } from "lucide-react";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { getDataSummary, type DataSummary } from "./reports.service";
import PageSkeleton from "../../components/ui/PageSkeleton";

const number = new Intl.NumberFormat("en-US");
const roleLabel = (role: string) => role === "superadmin" ? "Super Admin" : role.charAt(0).toUpperCase() + role.slice(1);

export default function DataSummaryPage() {
    const [report, setReport] = useState<DataSummary | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(false);
    const [from, setFrom] = useState("");
    const [to, setTo] = useState("");
    const [userId, setUserId] = useState("");
    const [source, setSource] = useState("");
    const [search, setSearch] = useState("");
    const [selectedUser, setSelectedUser] = useState<string | null>(null);
    const dateError = from && to && from > to ? "The From date cannot be later than the To date." : "";
    const load = async () => {
        if (dateError) return;
        setLoading(true); setError(false);
        try { setReport(await getDataSummary(Object.fromEntries(Object.entries({ from, to, user_id: userId, source, search }).filter(([, value]) => value)))); } catch { setError(true); } finally { setLoading(false); }
    };
    useEffect(() => { setSelectedUser(null); if (!dateError) void load(); }, [from, to, userId, source, search, dateError]);

    if (loading && !report) return <PageSkeleton cards={6} rows={6} />;
    if (error || !report) return <Card><CardContent className="flex flex-col items-center gap-3 py-12 text-center"><p>Unable to load data summary.</p><Button onClick={() => void load()}>Retry</Button></CardContent></Card>;
    const selectedImports = selectedUser ? report.imports.history.filter((item) => item.created_by === selectedUser) : report.imports.history;
    const maxCollected = Math.max(...report.users.map((user) => user.total_collected), 1);
    return <div className="space-y-6">
        <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Data Summary</h1><p className="mt-1 text-sm text-muted-foreground">Overview of citizen data collected by all administrators and super administrators.</p></div><Button variant="outline" size="icon" onClick={() => void load()} aria-label="Refresh data summary"><RefreshCw /></Button></div>
        <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm">From<input type="date" value={from} max={to || undefined} onChange={(event) => setFrom(event.target.value)} className="border-input bg-background mt-1 h-9 w-full rounded-md border px-2" /></label><label className="text-sm">To<input type="date" value={to} min={from || undefined} onChange={(event) => setTo(event.target.value)} className="border-input bg-background mt-1 h-9 w-full rounded-md border px-2" /></label><label className="text-sm">User<select value={userId} onChange={(event) => setUserId(event.target.value)} className="border-input bg-background mt-1 h-9 w-full rounded-md border px-2"><option value="">All users</option>{report.users.map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select></label><label className="text-sm">Source<select value={source} onChange={(event) => setSource(event.target.value)} className="border-input bg-background mt-1 h-9 w-full rounded-md border px-2"><option value="">All sources</option><option value="SINGLE_ENTRY">Single entry</option><option value="IMPORT">Excel import</option></select></label><label className="text-sm">Search<div className="relative mt-1"><Search className="absolute left-2 top-2 size-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name" className="border-input bg-background h-9 w-full rounded-md border pl-8 pr-2" /></div></label>{dateError && <p className="text-sm text-destructive sm:col-span-2 lg:col-span-5">{dateError}</p>}{loading && <p className="text-sm text-muted-foreground sm:col-span-2 lg:col-span-5">Updating report...</p>}</CardContent></Card>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Total Citizens" value={report.totals.total_citizens} icon={<Users />} /><Stat label="Single Entries" value={report.totals.single_entries} /><Stat label="Import Files" value={report.totals.import_files} /><Stat label="Imported Citizens" value={report.totals.imported_citizens} /></div>
        <div className="grid gap-4 sm:grid-cols-2"><Stat label="Total Admins" value={report.totals.total_admins} /><Stat label="Active Collectors" value={report.totals.active_collectors} /></div>
        <Card><CardHeader><CardTitle>Collection by User</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">User</th><th className="p-3">Role</th><th className="p-3">Single Entry</th><th className="p-3">Import Files</th><th className="p-3">Imported Citizens</th><th className="p-3">Total Collected</th></tr></thead><tbody>{report.users.map((user) => <tr className={`cursor-pointer border-b hover:bg-muted/50 ${selectedUser === user.id ? "bg-muted/50" : ""}`} key={user.id} onClick={() => setSelectedUser(selectedUser === user.id ? null : user.id)}><td className="p-3 font-medium">{user.name}</td><td className="p-3 text-muted-foreground">{roleLabel(user.role)}</td><td className="p-3">{number.format(user.single_entry)}</td><td className="p-3">{number.format(user.import_files)}</td><td className="p-3">{number.format(user.imported_citizens)}</td><td className="p-3 font-semibold">{number.format(user.total_collected)}</td></tr>)}<tr className="font-semibold"><td className="p-3" colSpan={2}>TOTAL</td><td className="p-3">{number.format(report.totals.single_entries)}</td><td className="p-3">{number.format(report.totals.import_files)}</td><td className="p-3">{number.format(report.totals.imported_citizens)}</td><td className="p-3">{number.format(report.totals.total_citizens)}</td></tr></tbody></table></CardContent></Card>
        <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Top Contributors</CardTitle></CardHeader><CardContent className="space-y-4">{report.users.map((user, index) => <div key={user.id}><div className="mb-1 flex justify-between text-sm"><span>{index < 3 ? ["1st", "2nd", "3rd"][index] : `${index + 1}th`} {user.name}</span><span className="font-semibold">{number.format(user.total_collected)}</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${(user.total_collected / maxCollected) * 100}%` }} /></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Collection Sources</CardTitle></CardHeader><CardContent className="space-y-5"><SourceBar label="Single Entry" value={report.totals.single_entries} total={report.totals.total_citizens} /><SourceBar label="Excel Import" value={report.totals.imported_citizens} total={report.totals.total_citizens} /></CardContent></Card></div>
        <Card><CardHeader><CardTitle>Import Summary</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><Stat label="Files Uploaded" value={report.imports.total_files} icon={<Upload />} /><Stat label="Imported Citizens" value={report.imports.imported_citizens} /><Stat label="Failed Records" value={report.imports.failed} /></CardContent></Card>
        <Card><CardHeader><CardTitle>Import History{selectedUser ? ` - ${report.users.find((user) => user.id === selectedUser)?.name || "User"}` : ""}</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">File Name</th><th className="p-3">User</th><th className="p-3">Records</th><th className="p-3">Failed</th><th className="p-3">Imported At</th></tr></thead><tbody>{selectedImports.map((item) => <tr className="border-b" key={item.id}><td className="p-3 font-medium">{item.file_name}</td><td className="p-3">{item.user_name}</td><td className="p-3">{number.format(item.total_rows)}</td><td className="p-3">{number.format(item.failed_rows || item.invalid_rows || 0)}</td><td className="p-3 text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{selectedImports.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No imports found.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Recent Collection Activity</CardTitle></CardHeader><CardContent className="space-y-3">{report.recent.map((item) => <div className="flex items-center gap-3 border-b pb-3 last:border-0" key={item.id}><Users className="size-4 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.user_name} <span className="font-normal text-muted-foreground">{item.action === "IMPORT" ? "imported citizens through Excel" : item.action === "CREATE" ? "added a citizen through single entry" : `${item.action.toLowerCase()}d a citizen`}</span></p><p className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</p></div></div>)}</CardContent></Card>
    </div>;
}

function Stat({ label, value, icon }: { label: string; value: number; icon?: React.ReactNode }) { return <Card><CardContent className="flex items-center gap-3"><>{icon}</><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{number.format(value)}</p></div></CardContent></Card>; }
function SourceBar({ label, value, total }: { label: string; value: number; total: number }) { return <div><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span className="font-semibold">{number.format(value)}</span></div><div className="h-3 rounded-full bg-muted"><div className="h-3 rounded-full bg-primary" style={{ width: `${total ? (value / total) * 100 : 0}%` }} /></div></div>; }